[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "megatransformer"
version = "0.1.0.dev49"
authors = [
    { name = "Justin Hartmann", email = "zadarimm@gmail.com" },
]
description = "MegaTransformer: customizable, huggingface-friendly transformer package."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = [
]

[project.optional-dependencies]
dev = [
]
